### ISSUE TITLE
Russound RIO intergration not detecting Zone 8 on MCA-88 in HA 2024.8

### ISSUE THREAD

**Issue by brettcp** [noahhusby/aiorussound#13]
I just updated to HA 2024.8 with the new Russound RIO integration on my existing MCA-88 (Firmware: 04.07.00).  I removed "russound_rio" from configuration.yaml and restarted as instructed.  The Russound RIO add-on is present but I only have 7 entities (zones) instead of the 8 I previously had.  Zone 8 is now missing, which was previously present and working as expected before the 2024.8 update.

I've tried the following:

- Power cycled the MCA-88 and rebooted HA.

- Deleted the Russound RIO integration, restarted HA, re-added the Russound RIO integration, then restarted HA again.

- Disabled and re-enabled Zone 8 on the MCA-88.

- Renamed Zone 8 from "Garage" to "Zone 8" within the MCA-88 just to be sure it wasn't some issue with the zone name.

Zones 1-7 appear to be working as expected.

Any ideas?  I've attached the debug log here which doesn't show any activity for Zone 8.

[home-assistant_russound_rio_2024-08-07T23-53-26.410Z.log](https://github.com/user-attachments/files/16535797/home-assistant_russound_rio_2024-08-07T23-53-26.410Z.log)

Thanks!

**Comment by noahhusby** [comment]
Hi @brettcp,

Thanks for fetching the debug log.

This is a simple bug with the range function (forget the inclusivity of the last zone). I've written a patch and will open a PR for home assistant. 

FYI, general rule of thumb is to open issues with the Home Assistant integration on the [@home-assistant/core](https://github.com/home-assistant/core) repository. I'm the code-owner for the integration so I get pinged over there as well.

**Comment by brettcp** [comment]
> Hi @brettcp,
> 
> Thanks for fetching the debug log.
> 
> This is a simple bug with the range function (forget the inclusivity of the last zone). I've written a patch and will open a PR for home assistant.
> 
> FYI, general rule of thumb is to open issues with the Home Assistant integration on the [@home-assistant/core](https://github.com/home-assistant/core) repository. I'm the code-owner for the integration so I get pinged over there as well.

Thank you, I applied the patch and Zone 8 is now working as expected.

Thanks for the heads-up on posting in the other repository, I'll do that from now on.

**Comment by noahhusby** [comment]
Reopening until patch is merged into HA

**Comment by noahhusby** [comment]
The change has been merged and will be released in HA Patch 2024.8.1
