### ISSUE TITLE
Entities Active Source Attributes Issue

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [noahhusby/aiorussound#34]
Since the HA Core 2024.9.1 update, zone entities are not returning the active source, but rather the 1st configured source on the Russound unit.

attributes.source previously returned the active source for a zone, but now displays the first source configured on the russound device.

**Comment by noahhusby** [comment]
This was an issue caused by the re-write of the models structure in the latest version of the library. It has since been addressed and while be released in the next HA patch update. I'll leave this open until that change is merged.

**Comment by noahhusby** [comment]
Also just FYI, if there is an issue within the Russound RIO integration on Home Assistant, please open a bug report on the HA repo and I'll respond there.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
Got it. Good to hear it's already fixed.

**Comment by noahhusby** [comment]
@zsQ8ymRSY8B4owpdCvTRdkz8rQUK The fix was released in Home Assistant 2024.9.2. Please update and confirm that it's working correctly.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
@noahhusby Confirmed. Latest update fixed the problem.

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
@noahhusby Confirmed. Latest update fixed the problem.
